/// Generated by Flutter GetX Starter on 2022-02-16 21:02
import 'dart:io';
import 'package:flutter/widgets.dart';

extension FontWeightExtension on FontWeight {
  FontWeight get auto {
    if (Platform.isAndroid && this == FontWeight.bold) {
      return FontWeight.w500;
    }
    return this;
  }
}