/// Generated by Flutter GetX Starter on 2022-02-16 21:02
import 'package:checkino/app/pages/home/home_binding.dart';
import 'package:checkino/app/pages/home/home_page.dart';
import 'package:checkino/app/pages/splash/binding.dart';
import 'package:checkino/app/pages/splash/view.dart';
import 'package:get/get.dart';

class Routes {
  static const HOME = '/home';
  static const SPLASH = '/splash';

  static final routes = [
    GetPage(
      name: Routes.HOME,
      page: () => HomePage(),
      binding: HomeBinding(),
    ),
    GetPage(
      name: Routes.SPLASH,
      page: () => SplashPage(),
      binding: SplashBinding(),
    ),
  ];
}